/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AppRouteImport } from "./routes/_app";
import { Route as AppAboutRouteImport } from "./routes/_app/about";
import { Route as AppArticlesSlugRouteImport } from "./routes/_app/articles.$slug";
import { Route as AppIndexRouteImport } from "./routes/_app/index";
import { Route as AppProfileSlugRouteImport } from "./routes/_app/profile.$slug";
import { Route as AppSuggestRouteImport } from "./routes/_app/suggest";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as LoginRouteImport } from "./routes/login";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any);
const AppSuggestRoute = AppSuggestRouteImport.update({
  id: "/suggest",
  path: "/suggest",
  getParentRoute: () => AppRoute,
} as any);
const AppAboutRoute = AppAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => AppRoute,
} as any);
const AppProfileSlugRoute = AppProfileSlugRouteImport.update({
  id: "/profile/$slug",
  path: "/profile/$slug",
  getParentRoute: () => AppRoute,
} as any);
const AppArticlesSlugRoute = AppArticlesSlugRouteImport.update({
  id: "/articles/$slug",
  path: "/articles/$slug",
  getParentRoute: () => AppRoute,
} as any);

export interface FileRoutesByFullPath {
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/about": typeof AppAboutRoute;
  "/suggest": typeof AppSuggestRoute;
  "/": typeof AppIndexRoute;
  "/articles/$slug": typeof AppArticlesSlugRoute;
  "/profile/$slug": typeof AppProfileSlugRoute;
}
export interface FileRoutesByTo {
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/about": typeof AppAboutRoute;
  "/suggest": typeof AppSuggestRoute;
  "/": typeof AppIndexRoute;
  "/articles/$slug": typeof AppArticlesSlugRoute;
  "/profile/$slug": typeof AppProfileSlugRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_app": typeof AppRouteWithChildren;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/_app/about": typeof AppAboutRoute;
  "/_app/suggest": typeof AppSuggestRoute;
  "/_app/": typeof AppIndexRoute;
  "/_app/articles/$slug": typeof AppArticlesSlugRoute;
  "/_app/profile/$slug": typeof AppProfileSlugRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/dashboard"
    | "/login"
    | "/about"
    | "/suggest"
    | "/"
    | "/articles/$slug"
    | "/profile/$slug";
  fileRoutesByTo: FileRoutesByTo;
  to: "/dashboard" | "/login" | "/about" | "/suggest" | "/" | "/articles/$slug" | "/profile/$slug";
  id:
    | "__root__"
    | "/_app"
    | "/dashboard"
    | "/login"
    | "/_app/about"
    | "/_app/suggest"
    | "/_app/"
    | "/_app/articles/$slug"
    | "/_app/profile/$slug";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/suggest": {
      id: "/_app/suggest";
      path: "/suggest";
      fullPath: "/suggest";
      preLoaderRoute: typeof AppSuggestRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/about": {
      id: "/_app/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AppAboutRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/profile/$slug": {
      id: "/_app/profile/$slug";
      path: "/profile/$slug";
      fullPath: "/profile/$slug";
      preLoaderRoute: typeof AppProfileSlugRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/articles/$slug": {
      id: "/_app/articles/$slug";
      path: "/articles/$slug";
      fullPath: "/articles/$slug";
      preLoaderRoute: typeof AppArticlesSlugRouteImport;
      parentRoute: typeof AppRoute;
    };
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute;
  AppSuggestRoute: typeof AppSuggestRoute;
  AppIndexRoute: typeof AppIndexRoute;
  AppArticlesSlugRoute: typeof AppArticlesSlugRoute;
  AppProfileSlugRoute: typeof AppProfileSlugRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppSuggestRoute: AppSuggestRoute,
  AppIndexRoute: AppIndexRoute,
  AppArticlesSlugRoute: AppArticlesSlugRoute,
  AppProfileSlugRoute: AppProfileSlugRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";

import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
